### ISSUE TITLE
Tests for XDG_SESSION_TYPE will always revert to Wayland

### ISSUE THREAD

**Issue by usonianhorizon** [raffaem/cppath#1]
I believe that in the tests for XDG_SESSION_TYPE the equality operator should have spaces around it, i.e., `$XDG_SESSION_TYPE== wayland"` should be `$XDG_SESSION_TYPE == "wayland"`.  Similarly for x11.  In my  FreeBSD 13 installation it always reverts to Wayland and wl-copy is not installed.

**Comment by raffaelemancuso** [comment]
You are right.

shellcheck complains:
```
In cppath line 35:
		if [ $XDG_SESSION_TYPE=="wayland" ]; then
                     ^---------------^ SC2086 (info): Double quote to prevent globbing and word splitting.
                                      ^-- SC2077 (error): You need spaces around the comparison operator.
```

See also: https://stackoverflow.com/questions/15365307/why-does-adding-spaces-around-bash-comparison-operator-change-the-result
